services:
  status-page:
    image: twinproduction/gatus:latest
    container_name: gatus
    restart: unless-stopped
    ports: ["3230:8080"]
    volumes:
      - ./config.yaml:/config/config.yaml:ro
